module.exports = {
    title: "cartes.gouv.fr",
    url: "https://cartes.gouv.fr/documentation",
    contact_form_url: "https://cartes.gouv.fr/nous-ecrire",
    site_url: "https://ignf.github.io/cartes.gouv.fr-documentation",
    newsletter: [
        {
            url: "",
            title: "",
            description: "",
        },
    ],
    facebook_url: "",
    mastodon_url: "",
    twitter_url: "",
    instagram_url: "",
    linkedin_url: "",
    youtube_url: "",
    peertube_url: "",
    github_url: "",
    sourcehut_url: "",
    repository_url: "https://github.com/IGNF/cartes.gouv.fr-documentation",
    language: "fr",
    description: "Documentation",
    author: {
        name: "IGN",
        email: "geoplateforme@ign.fr",
        url: "https://url_du_service.gouv.fr/",
    },
    service: "Institut National de l'Information Géographique et Forestière (IGN)",
};
